package com.solutioninventors.tournament.GUI.controller;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

public class ErrorController {
	@FXML
	private AnchorPane rootPane;
	@FXML
	private Label lblError;
	@FXML
	private Text txtErrorDetail;

	// Event Listener on Button.onAction
	@FXML
	public void next(ActionEvent event) {
		// TODO Autogenerated
	}
}
