package com.solutioninventors.tournament.GUI.views;

import javafx.fxml.FXML;

import javafx.scene.control.TextArea;

import javafx.scene.layout.AnchorPane;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TreeView;

import javafx.scene.input.ContextMenuEvent;

public class HelpController {
	@FXML
	private AnchorPane rootPane;
	@FXML
	private TreeView treeView;
	@FXML
	private TextArea txtArea;

	// Event Listener on TreeView[#treeView].onContextMenuRequested
	@FXML
	public void mouseClicked(ContextMenuEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TreeView[#treeView].onMouseClicked
	@FXML
	public void mouseClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
